---
title: "About Me"
---
# Interests and Hobbies:

### Sports:

**Cricket:**    
I have been playing cricket since my childhood. Even though not at a professional level I have loved playing the game. I also follow international cricket.  

**Volleyball:**  
I also play volleyball. I like to play the position of a setter. I started playing this in my high school days and trust me I was really bad at this. But now I think I play decent volleyball.   

### Music:

**Instruments:**  
I play Tabla. I have learnt classical Tabla for about two to three years long back. But after that I have just played Tabla as a supporting instrument. I would like to learn a couple more instruments like Guitar and Piano.  

**Listening:**  
This depends a lot on my mood and also probably my surroundings. My favorite artists include Arctic Monkeys, Green Day, AC/DC, Linkin Park, Maneskin, One Republic and more. I also occasionally listen to Bollywood and Sandalwood. Favorite singers here would include Arijit Singh, Sonu Nigam, Shreya Ghoshal, Vijay Prakash, Sanjith Hegde and more.  

### Entertainment:  

**Yakshagana:**  
This is a sort of play that is very popular in coastal Karnataka. I used to take part in this in my highschool days. Roles I played include Nakula, Krishna, Drupada and Valmiki. I do not enjoy watching this as much as I enjoy playing a role in this.  

**Manga/Anime:**  
I also love watching anime and reading manga. My first anime was Naruto. My first manga was Jujutsu Kaisen and I started reading this because I got some spoilers and I definitely do not like them. So I caught up to the manga. And then I continued reading different mangas based on my friends recommendations. Manga I read or anime I watched include One Piece, Demon Slayer, Haikyu, Akame ga kill, Solo Leveling, Omniscient Reader's Viewpoint, Ao Ashi, Anohana, Vinland Saga and many more. 



